server:
  port: 443
  ssl:
    key-password: '#Haslo123'
    key-store-password: '#Haslo123'
    key-store: classpath:keystore.jks
    key-store-type: pkcs12
logging:
  file:
    path: /var/log
spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost:5432}/szamka
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  cache:
    jcache:
      config: classpath:ehcache.xml
  flyway:
    enabled: true
    check-location: true
    locations: classpath:db/postgres
jwt:
  secret: sfasf!@jie42%$jas12432ed
  expirationTime: 3600000

