server:
  port: ${PORT:8000}
spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/szamka
#    username: postgres
#    password: postgres
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  sql:
    init:
      mode: always
  cache:
    jcache:
      config: classpath:ehcache.xml
jwt:
  secret: sfasf!@jie42%$jas12432ed
  expirationTime: 3600000

